# Generated by Django 5.0.4 on 2024-04-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Component',
            new_name='ProductComponent',
        ),
    ]
