# Generated by Django 5.0.4 on 2024-04-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_aa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AA',
        ),
    ]
