# Generated by Django 5.0.4 on 2024-04-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_aa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='ComponentInfor',
            new_name='Component',
        ),
        migrations.RenameModel(
            old_name='OrderInfor',
            new_name='Order',
        ),
        migrations.DeleteModel(
            name='AA',
        ),
    ]
