# Generated by Django 5.0.4 on 2024-04-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_product_rename_componentinfor_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
