# Generated by Django 5.0.4 on 2024-04-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_remove_order_order_date_alter_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
