# Generated by Django 5.0.4 on 2024-04-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Password',
            new_name='Login',
        ),
    ]
