# Generated by Django 5.0.4 on 2024-04-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_rename_password_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
